[package]
name = "network-stalker"
version = "0.1.0"
authors = ["EdJoPaTo <rust-package@edjopato.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
regex = "1.3"

[dependencies.clap]
version = "2.33"
features = ["wrap_help"]

[dependencies.paho-mqtt]
version = "0.7"
default-features = false
# Add "ssl" to the features if you need ssl support
features = ["bundled", "build_bindgen"]
