[package]
name = "network-stalker"
version = "0.3.0"
authors = ["EdJoPaTo <rust-package@edjopato.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
rumqttc = "0.2"

[dependencies.clap]
version = "2.33"
features = ["wrap_help"]
