[package]
name = "network-stalker"
description = "Tries to reach hosts on the network and reports their online status to MQTT"
version = "0.4.3"
license = "MIT"
authors = ["EdJoPaTo <rust-package@edjopato.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
# See https://doc.rust-lang.org/rustc/codegen-options/index.html
codegen-units = 1
lto = true

[dependencies]
chrono = "0.4"
rumqttc = "0.7"

[dependencies.clap]
version = "2.33"
features = ["wrap_help"]
